/*  Mazer5D: A Maze-Solving Game
Copyright (C) 2008-2013 Eric Ahnell

Any questions should be directed to the author via email at: products@puttysoftware.com
 */
package com.puttysoftware.mazer5d.objectmodel;

public enum MazeObjectType {
    GROUND,
    FIELD,
    CHARACTER,
    KEY,
    LOCK,
    SINGLE_USE,
    INFINITE_USE,
    LETTER,
    INVENTORYABLE,
    PASS,
    TELEPORT,
    INVISIBLE,
    RANDOM,
    WALL,
    USABLE,
    WAND,
    MOVABLE,
    BOOTS,
    INVENTORY_MODIFIER,
    BUTTON,
    TOGGLABLE,
    TRAP,
    TRIGGER_TRAP,
    TRIGGERED,
    GEM,
    BARRIER,
    CONTAINER,
    CONTAINABLE,
    TRANSIENT,
    BOW,
    FREEZABLE,
    BURNABLE,
    POISONABLE,
    SHOCKABLE,
    FREEZING,
    BURNING,
    POISONOUS,
    SHOCKING,
    GENERATOR,
    TEXT_HOLDER,
    MULTIPLE_USE,
    POTION,
    PROGRAMMABLE_USE,
    TIME_MODIFIER,
    SCORE_INCREASER,
    AMULET,
    LIGHT_MODIFIER,
    BREAKABLE,
    SUPPORTS_MOVING,
    LEVEL_CHANGE,
    IMMUTABLE,
    WINNER,
    CONDITIONAL,
    CHAIN_LINKED,
    TWO_WAY,
    AUTO_USE,
    USED_ON_COLLIDE,
    BOMB,
    ALLOWS_ARROWS,
    BLOCKS_SIGHT,
    CHAIN_REACTION,
    USED_ON_APPROACH,
    HEALTH_CHANGE,
    AUTO_MOVE,
    MOVE_RESTRICTION,
    GHOSTLY
}
