/*  Mazer5D: A Maze-Solving Game
Copyright (C) 2008-2013 Eric Ahnell

Any questions should be directed to the author via email at: products@puttysoftware.com
 */
package com.puttysoftware.mazer5d.objectmodel;

public enum MazeObjectType {
    GROUND,
    FIELD,
    CHARACTER,
    PASS_THROUGH,
    KEY,
    LOCK,
    SINGLE_USE,
    UNLOCKED_LOSE_KEY,
    INFINITE_USE,
    UNLOCKED_KEEP_KEY,
    PLUG,
    PORT,
    INVENTORYABLE,
    PASS,
    TELEPORT,
    INVISIBLE_TELEPORT,
    RANDOM,
    RANDOM_INVISIBLE_TELEPORT,
    WALL,
    USABLE,
    WAND,
    MOVABLE,
    BOOTS,
    INVENTORY_MODIFIER,
    BUTTON,
    TOGGLE_WALL,
    TRAP,
    WALL_TRAP,
    TRAPPED_WALL,
    GEM,
    BARRIER,
    CONTAINER,
    CONTAINABLE,
    TRANSIENT,
    BOW,
    REACTS_TO_ICE,
    REACTS_TO_FIRE,
    REACTS_TO_POISON,
    REACTS_TO_SHOCK,
    GENERATOR,
    TEXT_HOLDER,
    MULTIPLE_USE,
    UNLOCKED_LOSE_MULTIPLE_KEYS,
    POTION,
    PROGRAMMABLE_USE,
    UNLOCKED_LOSE_CHOSEN_KEY,
    TIME_MODIFIER,
    SCORE_INCREASER,
    AMULET,
    LIGHT_MODIFIER,
    PLAIN_WALL,
    EMPTY_SPACE,
    BREAKABLE_WALL
}
